version: "3.8"

services:
  telegram-downloader-bot:
    build: .
    container_name: media-downloader-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
